// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
///
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAy341ENmyKC-pe0_paYoekxL9iQiOHSsY',
    appId: '1:489174316062:web:abf8f30e153bbf5e92ea0f',
    messagingSenderId: '489174316062',
    projectId: 'well-5878d',
    authDomain: 'well-5878d.firebaseapp.com',
    storageBucket: 'well-5878d.firebasestorage.app',
    measurementId: 'G-24Y2MP7FG4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGeISOijPKsQexewLuXC433mF_n7UZrSk',
    appId: '1:489174316062:android:02117fc5c413df2f92ea0f',
    messagingSenderId: '489174316062',
    projectId: 'well-5878d',
    storageBucket: 'well-5878d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhxxxRXbnEBoA9ojDO-yCYpJ35UiIsN7M',
    appId: '1:489174316062:ios:d99e1f3e0d19559792ea0f',
    messagingSenderId: '489174316062',
    projectId: 'well-5878d',
    storageBucket: 'well-5878d.firebasestorage.app',
    androidClientId: '489174316062-evbkjtid015icluilijtupsmqvnft3dv.apps.googleusercontent.com',
    iosClientId: '489174316062-dnnbtthd7q05gbec7pp5d46q486seui4.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhxxxRXbnEBoA9ojDO-yCYpJ35UiIsN7M',
    appId: '1:489174316062:ios:d99e1f3e0d19559792ea0f',
    messagingSenderId: '489174316062',
    projectId: 'well-5878d',
    storageBucket: 'well-5878d.firebasestorage.app',
    iosBundleId: 'com.example.untitled1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAy341ENmyKC-pe0_paYoekxL9iQiOHSsY',
    appId: '1:489174316062:web:9e62fc387c07f2c992ea0f',
    messagingSenderId: '489174316062',
    projectId: 'well-5878d',
    authDomain: 'well-5878d.firebaseapp.com',
    storageBucket: 'well-5878d.firebasestorage.app',
    measurementId: 'G-6N4D7GTD5Y',
  );

}